document.addEventListener('DOMContentLoaded', () => {
    const videoListContainer = document.getElementById('video-list');

    // Fetch the manifest file generated by the GitHub Action
    fetch('/public/videos.json')
        .then(response => {
            if (!response.ok) {
                throw new Error('Video manifest not found. Download a video to generate it.');
            }
            return response.json();
        })
        .then(videos => {
            if (videos.length === 0) {
                videoListContainer.innerHTML = '<p>No videos downloaded yet. Run the "Download YouTube Video" action in GitHub.</p>';
                return;
            }

            videos.forEach(video => {
                const card = document.createElement('div');
                card.className = 'video-card';

                card.innerHTML = `
                    <h3>${video.title}</h3>
                    <p>By: ${video.author}</p>
                    <video controls preload="metadata">
                        <source src="${video.path}" type="video/mp4">
                        Your browser does not support the video tag.
                    </video>
                `;
                videoListContainer.appendChild(card);
            });
        })
        .catch(error => {
            console.error('Error loading videos:', error);
            videoListContainer.innerHTML = `<p style="color: #e53e3e;">${error.message}</p>`;
        });
});