name: 🎬 Process YouTube Video Request

on:
  repository_dispatch:
    types: [trigger-youtube-download] # Must match event_type in server.js

jobs:
  download-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytubefix requests

      - name: Run video download script
        env:
          JOB_ID: ${{ github.event.client_payload.jobId }}
          VIDEO_URL: ${{ github.event.client_payload.videoUrl }}
          RENDER_APP_URL: ${{ secrets.RENDER_APP_URL }}
          PROGRESS_UPDATE_SECRET: ${{ secrets.PROGRESS_UPDATE_SECRET }}
        run: python scripts/download_video.py

      - name: Commit and push new video
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add public/videos/*.mp4 public/videos/*.mp3 public/videos.json
          # Commit only if there are changes to commit
          if ! git diff-index --quiet HEAD; then
            git commit -m "BOT: 🤖 Add video for job ${{ github.event.client_payload.jobId }}"
            git push
          else
            echo "No changes to commit."
          fi